name: 'Merge Remote Pull Request'
description: 'Merge pull request across repositories and return the body of the pull request'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  owner:
    description: 'Owner of the target repository.'
    required: true
  repo:
    description: 'Name of the target repository.'
    required: true
  branch:
    description: 'Branch to merge.'
    required: true
  token:
    description: 'API token'
    required: false
outputs:
  solutions:
    description: 'solutions names'
