name: 'Merge Remote Pull Request'
description: 'Creates a pull request across repositories.'
runs:
  using: 'node12'
  main: 'index.js'
inputs:
  owner:
    description: 'Owner of the target repository.'
    required: true
  repo:
    description: 'Name of the target repository.'
    required: true
  branch:
    description: 'Branch to merge.'
    required: true
  token:
    description: 'API token'
    required: false
